secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  license_product_data:
    file: ./secrets/license_product_data.txt
  aws_secret_key:
    file: ./secrets/aws_secret_key.txt
  password_encryption_key:
    file: ./secrets/password_encryption_key.txt

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-local
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: ss-test-onestack
    ports:
      - "27018:27017"
    volumes:
      - ./mongodata:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: redis-local
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - discovery.type=single-node
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  smartsearch-distroless:
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.distroless
    env_file:
      - .env.config
      - .env.secrets
    environment:
      - NODE_ENV=production
    secrets:
      - jwt_secret
      - license_product_data
      - aws_secret_key
      - password_encryption_key
    ports:
      - 9080:9080
      - 9081:9081
      - 9085:9085
    volumes:
      - ./logs:/tmp

volumes:
  esdata:
    driver: local
